# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hat < Formula
  desc "Hat is a CLI tool which provides the ability to download various files directly from Habbo."
  homepage ""
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Izzxt/hat/releases/download/v0.1.0/hat_0.1.0_darwin_arm64.tar.gz"
      sha256 "d687a0182a6544823f742a4bc5b14a02c6ed8c09f26616ed7a589e512079118a"

      def install
        bin.install "hat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Izzxt/hat/releases/download/v0.1.0/hat_0.1.0_darwin_x86_64.tar.gz"
      sha256 "ff381255192d95c480db6a564eeb99e92f4c2ac6f52a9ab3d803a6317d25957d"

      def install
        bin.install "hat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Izzxt/hat/releases/download/v0.1.0/hat_0.1.0_linux_arm64.tar.gz"
      sha256 "a3b8fa834c297d4ae77b1910c944f47b5466e5bd2ea1bc2859462053f454da3d"

      def install
        bin.install "hat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Izzxt/hat/releases/download/v0.1.0/hat_0.1.0_linux_x86_64.tar.gz"
      sha256 "b73c2c9e5a5c5e7d2ee619db88c7c08b100ac5b3f0129ec3c0dfdfda96398381"

      def install
        bin.install "hat"
      end
    end
  end

  test do
    system "#{bin}/hat -h"
  end
end
