# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hat < Formula
  desc "Hat is a CLI tool which provides the ability to download various files directly from Habbo."
  homepage ""
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Izzxt/hat/releases/download/v0.1.1/hat_0.1.1_darwin_x86_64.tar.gz"
      sha256 "cd1ef33e9effa255c23e38b570688841e2393598864f1ff5cf01070ba4d55dee"

      def install
        bin.install "hat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Izzxt/hat/releases/download/v0.1.1/hat_0.1.1_darwin_arm64.tar.gz"
      sha256 "6fffb3f12611bdf36a9add91933cd8fd3314bd70a8503c38f25777ea4c523672"

      def install
        bin.install "hat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Izzxt/hat/releases/download/v0.1.1/hat_0.1.1_linux_arm64.tar.gz"
      sha256 "5b8cc48c79429f8ec3fc98b6c643b00fe51b8f3f6870de1618e6e665095f6717"

      def install
        bin.install "hat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Izzxt/hat/releases/download/v0.1.1/hat_0.1.1_linux_x86_64.tar.gz"
      sha256 "aa2f4c5ee16cd8ef50eebd2c498c787317ea4c2ff03939b61c27e24045bb043f"

      def install
        bin.install "hat"
      end
    end
  end

  test do
    system "#{bin}/hat -h"
  end
end
