# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hat < Formula
  desc "Hat is a CLI tool which provides the ability to download various files directly from Habbo."
  homepage ""
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Izzxt/hat/releases/download/v0.1.0/hat_0.1.0_darwin_x86_64.tar.gz"
      sha256 "14fb6f33fa1f9e0e94fa35371bf6ec6d00ba99e4301e84fe14bc1364584f07d4"

      def install
        bin.install "hat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Izzxt/hat/releases/download/v0.1.0/hat_0.1.0_darwin_arm64.tar.gz"
      sha256 "a056449fdef7c9ee32e43e366fab096739fdf68dde01695bf63a07ce404b5222"

      def install
        bin.install "hat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Izzxt/hat/releases/download/v0.1.0/hat_0.1.0_linux_x86_64.tar.gz"
      sha256 "d4eb35ce155a58447967474cc420615597cd1880258762745ad4dd9c9b79c691"

      def install
        bin.install "hat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Izzxt/hat/releases/download/v0.1.0/hat_0.1.0_linux_arm64.tar.gz"
      sha256 "226a8d9091057cf5cd5acbe56d2a4060cedbae2f59df137cbff96c3286d40fc8"

      def install
        bin.install "hat"
      end
    end
  end

  test do
    system "#{bin}/hat -h"
  end
end
